source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UK-Police-iOS-SDK_Example', :exclusive => true do
  pod "UK-Police-iOS-SDK", :path => "../"
end

target 'UK-Police-iOS-SDK_Tests', :exclusive => true do
  pod "UK-Police-iOS-SDK", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
